<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>eaee99fa-fdec-46c1-8b4f-056769d8aeb4</UserSecretsId>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="2.0.3" />
    <PackageReference Include="FluentAssertions" Version="6.9.0" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Claims.Api\Claims.Api.csproj" />
    <ProjectReference Include="..\Claims.Domain\Claims.Domain.csproj" />
    <ProjectReference Include="..\Claims.Application\Claims.Application.csproj" />
    <ProjectReference Include="..\Claims.Infrastructure\Claims.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Fakes\Controllers\" />
    <Folder Include="Fakes\Filters\" />
    <Folder Include="Services\AuditingServices\" />
  </ItemGroup>

</Project>
